### ISSUE TITLE
Error when running

### ISSUE THREAD

**Issue by Bruceli-iscool** [iangaunt/electron#2]
src/ts/main.ts:2:24 - error TS1261: Already included file name '/Users/keli/Documents/GitHub/roguelike/src/ts/sprites/Player.ts' differs from file name '/Users/keli/Documents/GitHub/roguelike/src/ts/sprites/player.ts' only in casing.
  The file is in the program because:
    Imported via "./sprites/Player.js" from file '/Users/keli/Documents/GitHub/roguelike/src/ts/main.ts'
    Matched by default include pattern '**/*'

2 import { Player } from "./sprites/Player.js";

**Comment by iangaunt** [comment]
GitHub had not renamed the files to their proper casing. This has since been fixed. Please stash / delete your working copy and fetch a new copy with proper file casing.
